config/routes.rb
require 'sidekiq/web'
Photoboard::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  resources :memories
  resources :comments
  match '/process' => 'process#photo', as: "process"

  authenticated :user do
    mount Sidekiq::Web, at: "/sidekiq"
  end

  root :to => 'memories#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :memory_id, :text, :user_id
  belongs_to :memory
  belongs_to :user
end

app/models/memory.rb
class Memory < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  attr_accessible :photo, :remote_photo_url, :title, :marked_for_delete_at

  validates_uniqueness_of :md5hash, if:  ->(m){m.photo_changed?}
  before_validation :compute_hash, if: ->(m){m.photo_changed?}

  has_many :comments

  def compute_hash
    self.md5hash = Digest::MD5.hexdigest(photo.read)
  end
end

app/models/raw_photo.rb
class RawPhoto
  AWS::S3::Base.establish_connection!(
    access_key_id:      UPLOADERS::CONFIG[:aws_key],
    secret_access_key:  UPLOADERS::CONFIG[:aws_secret]
  )

  PREFIX = 'raw/'
  attr_accessor :object

  def self.files
    files = AWS::S3::Bucket.objects UPLOADERS::CONFIG[:bucket], prefix: PREFIX
    files.delete_if { |aws_file| aws_file.key.match /^#{PREFIX}$/}
    files.map { |aws_file| new(aws_file) }
  end

  def self.size
    files.size
  end

  def self.find_by_key key
     new AWS::S3::S3Object.find key, UPLOADERS::CONFIG[:bucket]
  end

  def initialize(object)
    self.object = object
  end

  def key
    self.object.key
  end

  def url
    object.url
  end

  def process!
    memory = Memory.new(remote_photo_url: url)
    if memory.save
      object.delete
    elsif memory.errors[:md5hash].present?
      puts "Duplicate Upload: #{memory.inspect}"
      object.delete
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.order( "created_at DESC" ).page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end



  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end



  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end


  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = current_user.comments.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @memory }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end



  def update
    @comment = current_user.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to memories_path, notice: 'Comment was successfully updated.' }
        format.json { render json: @comment }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
 layout "board", only: :index 



  def index
    @memories = Memory.order( "created_at DESC" ).page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memories }
    end
  end



  def show
    @memory = Memory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @memory }
    end
  end



  def new
    @memory = Memory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @memory }
    end
  end


  def edit
    @memory = Memory.find(params[:id])
  end



  def create
    @memory = Memory.new(params[:memory])

    respond_to do |format|
      if @memory.save
        format.html { redirect_to @memory, notice: 'Memory was successfully created.' }
        format.json { render json: @memory, status: :created, location: @memory }
      else
        format.html { render action: "new" }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end



  def update
    @memory = Memory.find(params[:id])

    respond_to do |format|
      if @memory.update_attributes(params[:memory])
        format.html { redirect_to memories_path, notice: 'Memory was successfully updated.' }
        format.json { render json: @memory }
      else
        format.html { render action: "edit" }
        format.json { render json: @memory.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @memory = Memory.find(params[:id])
    @memory.destroy

    respond_to do |format|
      format.html { redirect_to memories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/process_controller.rb
class ProcessController < ApplicationController

  def photo
    RawPhoto.files.each do |file|
      PhotoProcessor.perform_async file.key
    end
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
  def name_only email
    email.split('@')[0]
  end
end

app/views/comments/index.html.haml
%table.table.table-hover
  %tr
  - @comments.each do |comment|
    %tr
      %td= comment.user.email
      %td= link_to "Photo", comment.memory.photo_url
      %td= comment.text

      %td= link_to 'Edit', edit_comment_path(comment)
      %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/layouts/_common.html.haml
=content_for :head do
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %meta(name="user" content="#{current_user.try(:id)}")
    %title= content_for?(:title) ? yield(:title) : "Photoboard"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css')

    %link(href="/favicon.ico" rel="shortcut icon")

=content_for :flash do
  .row-fluid#flash-messages
    .span12
      = flash[:notice]
    .span12
      = flash[:errors]
      
=content_for :nav do
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        =link_to root_url, class: 'brand' do
          %span.logo Photoboard
        .container.nav-collapse
          %ul.nav.pull-right
            - if !current_user
              %li= link_to('Sign Up', new_user_registration_path)
              %li= link_to('Sign In', new_user_session_path)
            -else
              %li= link_to('Sign Out', destroy_user_session_path, :method => :delete)

=content_for :footer do
  %footer
    %p &copy; DappleBeforeDawn 2013

app/views/layouts/application.html.haml
=render '/layouts/common'
!!! 5
%html(lang="en")
  =yield :head

  %body
    = yield :nav

    .container-fluid
      = yield :flash

      = yield
    
      = yield :footer

    = javascript_include_tag "application"

app/views/layouts/board.html.haml
=render '/layouts/common'
!!! 5
%html.board(lang="en")
  =yield :head

  %body
    = yield :nav

    .container-fluid
      = yield :flash

      = yield
    
      = yield :footer

    = javascript_include_tag "application"

app/views/memories/_form.html.haml
= form_for @memory do |f|
  - if @memory.errors.any?
    #error_explanation
      %h2= "#{pluralize(@memory.errors.count, "error")} prohibited this memory from being saved:"
      %ul
        - @memory.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :photo
    = f.text_field :photo
  .actions
    = f.submit 'Save'

app/views/memories/_memory_form.html.haml
.memory
  = form_for memory, html: {'data-live-edit' => true} do |f|
    %dl.polaroid
      = link_to memory.photo_url(:display), rel: 'gallery' do
        %i.icon-zoom-in
      = link_to "#show-comments-#{memory.id}"  do
        %i.icon-pencil
      = hidden_field :memory, :marked_for_delete_at, value: false
      = f.check_box :marked_for_delete_at, {}, Time.now, false

      -#%span.push-pin
      %dd
        = image_tag memory.photo_url(:thumb), exif: true
      %dt 
        %div.memory-title= memory.title
        = f.text_field :title, class: 'memory-title'

  = form_for Comment.new(memory_id: memory.id), html: {'data-live-edit' => true} do |f|
    .comments-pad.behind
      .old-comments
        - memory.comments.each do |comment|
          %div.user-tag= "-- #{name_only comment.user.email} --"
          %p= comment.text

        .this-comment
          %div.user-tag= "-- #{name_only current_user.email} --"
          %p

      =f.hidden_field :memory_id
      =f.text_area :text

app/views/memories/edit.html.haml
%h1 Editing memory

= render 'form'

= link_to 'Show', @memory
\|
= link_to 'Back', memories_path

app/views/memories/index.html.haml
%div.tape [ #{RawPhoto.size} unprocessed photos - #{link_to 'Logs', '/sidekiq', class: 'accent'} ]
.infinite-container
  .infinite-content
    - @memories.each_slice(4) do |four_memories|
      .row-fluid
        - four_memories.each do |memory|
          .span3
            = render '/memories/memory_form', memory: memory 
  -#%tr
    -#%td= memory.photo
    -#%td= link_to 'Show', memory
    -#%td= link_to 'Edit', edit_memory_path(memory)
    -#%td= link_to 'Destroy', memory, :method => :delete, :data => { :confirm => 'Are you sure?' }
= paginate @memories 

app/views/memories/new.html.haml
%h1 New memory

= render 'form'

= link_to 'Back', memories_path

app/views/memories/show.html.haml
%p#notice= notice

%p
  %b Photo:
  = @memory.photo

= link_to 'Edit', edit_memory_path(@memory)
\|
= link_to 'Back', memories_path